/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwapForm: typeof import('./components/swap-form/index.vue')['default']
    SwapFormAccountInput: typeof import('./components/swap-form/AccountInput.vue')['default']
    SwapFormD9Input: typeof import('./components/swap-form/D9Input.vue')['default']
    SwapFormReceiverInput: typeof import('./components/swap-form/ReceiverInput.vue')['default']
    SwapFormSwapInfo: typeof import('./components/swap-form/SwapInfo.vue')['default']
    SwapFormTronInput: typeof import('./components/swap-form/TronInput.vue')['default']
  }
}
