/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlockchainSectionHeader: typeof import('./components/blockchain/section/Header.vue')['default']
    BlockchainSectionTable: typeof import('./components/blockchain/section/Table.vue')['default']
    BlockchainSectionVotes: typeof import('./components/blockchain/section/Votes.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    CoverWrapper: typeof import('./components/CoverWrapper.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    HomeSectionCommunity: typeof import('./components/home/section/Community.vue')['default']
    HomeSectionHeader: typeof import('./components/home/section/Header.vue')['default']
    HomeSectionHighlight: typeof import('./components/home/section/Highlight.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    TokensSectionHeader: typeof import('./components/tokens/section/Header.vue')['default']
    TokensSectionTable: typeof import('./components/tokens/section/Table.vue')['default']
  }
}
